In [7]:
import numpy as np
from sklearn import preprocessing 

data = np.array([[3,5],[7,4],[2,4]])
print(data)

#mean average
mean_value= data.mean(axis=0)
print(mean_value)

#Standard Deviation
std = data.std(axis=0)
print(std)

# Mean Removal
final_val = data - mean_value
print(final_val)
# print(final_val.mean(axis=0))
# print(final_val.std(axis=0))

# Scale
final = preprocessing.scale(data)
print(final)
print(final.mean(axis=0))
print(final_val.mean(axis=0))

[[3 5]
 [7 4]
 [2 4]]
[4.         4.33333333]
[2.1602469  0.47140452]
[[-1.          0.66666667]
 [ 3.         -0.33333333]
 [-2.         -0.33333333]]
[[-0.46291005  1.41421356]
 [ 1.38873015 -0.70710678]
 [-0.9258201  -0.70710678]]
[0.00000000e+00 5.92118946e-16]
[0.00000000e+00 2.96059473e-16]


In [21]:
import pandas as pd
import numpy as np
from sklearn import preprocessing 


df=pd.read_csv('table.csv')
print (df)
print('\n')

data = df[['Person','Male','Female']]
print(data)
print('\n')

print(data.mean(axis=0))
print(data.std(axis=0))
print('\n')

mean_remove_data = preprocessing.scale(data)
print(mean_remove_data.mean(axis=0))
print(mean_remove_data.std(axis=0))
print('\n')


   Year  Person   Male  Female
0  1980   18.33  22.25   25.12
1  1990   20.20  25.10   23.00
2  2000   35.10  32.40   25.32
3  2010   23.20  25.10   24.10
4  2020   23.20  21.10   24.40


   Person   Male  Female
0   18.33  22.25   25.12
1   20.20  25.10   23.00
2   35.10  32.40   25.32
3   23.20  25.10   24.10
4   23.20  21.10   24.40


Person    24.006
Male      25.190
Female    24.388
dtype: float64
Person    6.539853
Male      4.398068
Female    0.923861
dtype: float64


[-1.33226763e-16  7.54951657e-16  2.58092159e-15]
[1. 1. 1.]




#Scaling

In [25]:
data = np.array([[3,5],[7,4],[2,4]])
scaller_model = preprocessing.MinMaxScaler()

op1=scaller_model.fit(data)
print(op1)

op2 = op1.transform(data)
print(op2)


MinMaxScaler()
[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


In [26]:

data = np.array([[3,5],[7,4],[2,4]])
scaller_model = preprocessing.MinMaxScaler()
op=scaller_model.fit_transform(data)
print(op)


[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]
